sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
  # minimum supported version
  - "1.36.0"
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add rustfmt

script:
  - cargo build
  - cargo build --examples
  - cargo test
  - cargo fmt -- --check
  - python3 scripts/test.py --debug --verbose
  - cargo doc

after_success:
  - |
    [ ! $TRAVIS_BRANCH = master ] ||
    [ ! $TRAVIS_RUST_VERSION = stable ] ||
    scripts/doc-upload.sh

env:
  global:
    - secure: "BJ6uNVxdlIKjDAIXgN4ACL6eUHmrtXCf14b4nNDW/3SUBafGXWT0EulpUrHTiU0YRlUkyBYIweMdfIpweV7NKlW9Acdygo6QmdMDvht+mWtH4ctlfBXukLoKie7uYp12LkwEP9kRateQ4uXeBt3/JquAu+/+pWzl5t01xAlWQ6o="
