language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq boost1.55
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo pip install cpp-coveralls
script:
  - export CTEST_OUTPUT_ON_FAILURE=1
  - cmake -DCMAKE_BUILD_TYPE=gcov . && make && make test
after_success:
  - coveralls -e CMakeFiles -E ".*/test/.*" --gcov-options '\-lp'
